// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/auth/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname             string   `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedOn            string   `protobuf:"bytes,5,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a414a1b227848998, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

type SignUpUser struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpUser) Reset()         { *m = SignUpUser{} }
func (m *SignUpUser) String() string { return proto.CompactTextString(m) }
func (*SignUpUser) ProtoMessage()    {}
func (*SignUpUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a414a1b227848998, []int{1}
}

func (m *SignUpUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpUser.Unmarshal(m, b)
}
func (m *SignUpUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpUser.Marshal(b, m, deterministic)
}
func (m *SignUpUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpUser.Merge(m, src)
}
func (m *SignUpUser) XXX_Size() int {
	return xxx_messageInfo_SignUpUser.Size(m)
}
func (m *SignUpUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpUser.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpUser proto.InternalMessageInfo

func (m *SignUpUser) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *SignUpUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUser struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUser) Reset()         { *m = LoginUser{} }
func (m *LoginUser) String() string { return proto.CompactTextString(m) }
func (*LoginUser) ProtoMessage()    {}
func (*LoginUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a414a1b227848998, []int{2}
}

func (m *LoginUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUser.Unmarshal(m, b)
}
func (m *LoginUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUser.Marshal(b, m, deterministic)
}
func (m *LoginUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUser.Merge(m, src)
}
func (m *LoginUser) XXX_Size() int {
	return xxx_messageInfo_LoginUser.Size(m)
}
func (m *LoginUser) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUser.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUser proto.InternalMessageInfo

func (m *LoginUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupRequest struct {
	SignUpUser           *SignUpUser `protobuf:"bytes,1,opt,name=signUpUser,proto3" json:"signUpUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a414a1b227848998, []int{3}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetSignUpUser() *SignUpUser {
	if m != nil {
		return m.SignUpUser
	}
	return nil
}

type SignupResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a414a1b227848998, []int{4}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LoginRequest struct {
	LoginUser            *LoginUser `protobuf:"bytes,1,opt,name=loginUser,proto3" json:"loginUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a414a1b227848998, []int{5}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLoginUser() *LoginUser {
	if m != nil {
		return m.LoginUser
	}
	return nil
}

type LoginResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a414a1b227848998, []int{6}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*SignUpUser)(nil), "auth.SignUpUser")
	proto.RegisterType((*LoginUser)(nil), "auth.LoginUser")
	proto.RegisterType((*SignupRequest)(nil), "auth.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "auth.SignupResponse")
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
}

func init() { proto.RegisterFile("services/auth/auth.proto", fileDescriptor_a414a1b227848998) }

var fileDescriptor_a414a1b227848998 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0xab, 0xda, 0x40,
	0x14, 0xc5, 0x9b, 0xf8, 0xa7, 0xe6, 0x5a, 0x6d, 0x19, 0x5d, 0x04, 0xa1, 0x20, 0x59, 0x49, 0x41,
	0x53, 0x2c, 0x5d, 0xda, 0xd6, 0xae, 0x0b, 0x85, 0x88, 0x1b, 0x37, 0x65, 0x4c, 0x6e, 0x93, 0xa1,
	0x71, 0x26, 0xcd, 0xcc, 0xd4, 0xbe, 0xf5, 0xfb, 0xe2, 0x8f, 0x4c, 0x9c, 0x68, 0x1e, 0xc8, 0xdb,
	0x84, 0x9c, 0x99, 0x39, 0xf7, 0x77, 0xee, 0xe5, 0x82, 0x2f, 0xb1, 0xfc, 0xc7, 0x62, 0x94, 0x21,
	0xd5, 0x2a, 0x33, 0x9f, 0x55, 0x51, 0x0a, 0x25, 0x48, 0xb7, 0xfa, 0x0f, 0x1e, 0x1d, 0xe8, 0xee,
	0x25, 0x96, 0x64, 0x0c, 0x2e, 0x4b, 0x7c, 0x67, 0xee, 0x2c, 0x3a, 0x91, 0xcb, 0x12, 0x32, 0x83,
	0xc1, 0x6f, 0x9d, 0xe7, 0x9c, 0x9e, 0xd0, 0x77, 0xe7, 0xce, 0xc2, 0x8b, 0x1a, 0x4d, 0xa6, 0xd0,
	0xc3, 0x13, 0x65, 0xb9, 0xdf, 0x31, 0x17, 0xb5, 0xa8, 0x1c, 0x05, 0x95, 0xf2, 0x2c, 0xca, 0xc4,
	0xef, 0xd6, 0x0e, 0xab, 0xc9, 0x7b, 0x80, 0xb8, 0x44, 0xaa, 0x30, 0xf9, 0x25, 0xb8, 0xdf, 0x33,
	0xb7, 0xde, 0xe5, 0xe4, 0x27, 0x0f, 0x0e, 0x00, 0x3b, 0x96, 0xf2, 0x7d, 0x61, 0xa2, 0xdc, 0xa2,
	0x9d, 0x7b, 0x68, 0xf7, 0x1e, 0xba, 0xd3, 0x46, 0x07, 0x1b, 0xf0, 0x7e, 0x88, 0x94, 0x71, 0x53,
	0xba, 0xb1, 0x3b, 0xf7, 0xec, 0xee, 0x33, 0xfb, 0x16, 0x46, 0x55, 0x34, 0x5d, 0x44, 0xf8, 0x57,
	0xa3, 0x54, 0xe4, 0x23, 0x80, 0x6c, 0xb2, 0x9a, 0x3a, 0xc3, 0xf5, 0xbb, 0x95, 0x19, 0xec, 0xb5,
	0x87, 0xe8, 0xe6, 0x4d, 0xf0, 0x01, 0xc6, 0xb6, 0x84, 0x2c, 0x04, 0x97, 0x48, 0x7c, 0x78, 0x2d,
	0x75, 0x1c, 0xa3, 0x94, 0xa6, 0xc0, 0x20, 0xb2, 0x32, 0xd8, 0xc0, 0x1b, 0x93, 0xd6, 0xd2, 0x96,
	0xe0, 0xe5, 0x36, 0xfd, 0x05, 0xf6, 0xb6, 0x86, 0x35, 0x4d, 0x45, 0xd7, 0x17, 0xc1, 0x57, 0x18,
	0x5d, 0xec, 0x2f, 0x91, 0xaa, 0x51, 0x28, 0xf1, 0x07, 0xb9, 0x9d, 0xa4, 0x11, 0xeb, 0xff, 0x30,
	0xdc, 0x6a, 0x95, 0xed, 0xea, 0xad, 0x21, 0x9f, 0xa1, 0x5f, 0x47, 0x27, 0x93, 0x6b, 0x8b, 0xcd,
	0x2c, 0x66, 0xd3, 0xf6, 0x61, 0xcd, 0x0c, 0x5e, 0x91, 0x35, 0xf4, 0x4c, 0x0c, 0x42, 0x6e, 0xb2,
	0x5a, 0xd3, 0xa4, 0x75, 0x66, 0x3d, 0xdf, 0xbf, 0x1d, 0xbe, 0xa4, 0x4c, 0x65, 0xfa, 0xb8, 0x8a,
	0xc5, 0x29, 0xe4, 0x88, 0x79, 0x9c, 0x09, 0x9d, 0x64, 0xb4, 0x7c, 0x08, 0x8f, 0x3a, 0x49, 0x51,
	0x9d, 0x69, 0x9e, 0xa3, 0x5a, 0xd2, 0x82, 0x2d, 0xab, 0xad, 0xc6, 0x32, 0x6c, 0x2d, 0xf7, 0xb1,
	0x6f, 0x16, 0xfb, 0xd3, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0x01, 0x99, 0x55, 0xf4, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Signup(ctx context.Context, req *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _AuthService_Signup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/auth/auth.proto",
}
