// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/dataprocessing/dataProcessing.proto

package dataprocessing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountDailySnapshot struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	StartDayBalance      float64  `protobuf:"fixed64,4,opt,name=start_day_balance,json=startDayBalance,proto3" json:"start_day_balance,omitempty"`
	EndDayBalance        float64  `protobuf:"fixed64,5,opt,name=end_day_balance,json=endDayBalance,proto3" json:"end_day_balance,omitempty"`
	CashOut              float64  `protobuf:"fixed64,6,opt,name=cash_out,json=cashOut,proto3" json:"cash_out,omitempty"`
	CashIn               float64  `protobuf:"fixed64,7,opt,name=cash_in,json=cashIn,proto3" json:"cash_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDailySnapshot) Reset()         { *m = AccountDailySnapshot{} }
func (m *AccountDailySnapshot) String() string { return proto.CompactTextString(m) }
func (*AccountDailySnapshot) ProtoMessage()    {}
func (*AccountDailySnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{0}
}

func (m *AccountDailySnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDailySnapshot.Unmarshal(m, b)
}
func (m *AccountDailySnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDailySnapshot.Marshal(b, m, deterministic)
}
func (m *AccountDailySnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDailySnapshot.Merge(m, src)
}
func (m *AccountDailySnapshot) XXX_Size() int {
	return xxx_messageInfo_AccountDailySnapshot.Size(m)
}
func (m *AccountDailySnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDailySnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDailySnapshot proto.InternalMessageInfo

func (m *AccountDailySnapshot) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AccountDailySnapshot) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountDailySnapshot) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *AccountDailySnapshot) GetStartDayBalance() float64 {
	if m != nil {
		return m.StartDayBalance
	}
	return 0
}

func (m *AccountDailySnapshot) GetEndDayBalance() float64 {
	if m != nil {
		return m.EndDayBalance
	}
	return 0
}

func (m *AccountDailySnapshot) GetCashOut() float64 {
	if m != nil {
		return m.CashOut
	}
	return 0
}

func (m *AccountDailySnapshot) GetCashIn() float64 {
	if m != nil {
		return m.CashIn
	}
	return 0
}

type AccountMonthlySnapshot struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	StartMonthBalance    float64  `protobuf:"fixed64,4,opt,name=start_month_balance,json=startMonthBalance,proto3" json:"start_month_balance,omitempty"`
	EndMonthBalance      float64  `protobuf:"fixed64,5,opt,name=end_month_balance,json=endMonthBalance,proto3" json:"end_month_balance,omitempty"`
	CashOut              float64  `protobuf:"fixed64,6,opt,name=cash_out,json=cashOut,proto3" json:"cash_out,omitempty"`
	CashIn               float64  `protobuf:"fixed64,7,opt,name=cash_in,json=cashIn,proto3" json:"cash_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountMonthlySnapshot) Reset()         { *m = AccountMonthlySnapshot{} }
func (m *AccountMonthlySnapshot) String() string { return proto.CompactTextString(m) }
func (*AccountMonthlySnapshot) ProtoMessage()    {}
func (*AccountMonthlySnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{1}
}

func (m *AccountMonthlySnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMonthlySnapshot.Unmarshal(m, b)
}
func (m *AccountMonthlySnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMonthlySnapshot.Marshal(b, m, deterministic)
}
func (m *AccountMonthlySnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMonthlySnapshot.Merge(m, src)
}
func (m *AccountMonthlySnapshot) XXX_Size() int {
	return xxx_messageInfo_AccountMonthlySnapshot.Size(m)
}
func (m *AccountMonthlySnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMonthlySnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMonthlySnapshot proto.InternalMessageInfo

func (m *AccountMonthlySnapshot) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AccountMonthlySnapshot) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountMonthlySnapshot) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *AccountMonthlySnapshot) GetStartMonthBalance() float64 {
	if m != nil {
		return m.StartMonthBalance
	}
	return 0
}

func (m *AccountMonthlySnapshot) GetEndMonthBalance() float64 {
	if m != nil {
		return m.EndMonthBalance
	}
	return 0
}

func (m *AccountMonthlySnapshot) GetCashOut() float64 {
	if m != nil {
		return m.CashOut
	}
	return 0
}

func (m *AccountMonthlySnapshot) GetCashIn() float64 {
	if m != nil {
		return m.CashIn
	}
	return 0
}

type GetAccountDailySnapshotsRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountDailySnapshotsRequest) Reset()         { *m = GetAccountDailySnapshotsRequest{} }
func (m *GetAccountDailySnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountDailySnapshotsRequest) ProtoMessage()    {}
func (*GetAccountDailySnapshotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{2}
}

func (m *GetAccountDailySnapshotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDailySnapshotsRequest.Unmarshal(m, b)
}
func (m *GetAccountDailySnapshotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDailySnapshotsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountDailySnapshotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDailySnapshotsRequest.Merge(m, src)
}
func (m *GetAccountDailySnapshotsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountDailySnapshotsRequest.Size(m)
}
func (m *GetAccountDailySnapshotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDailySnapshotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDailySnapshotsRequest proto.InternalMessageInfo

func (m *GetAccountDailySnapshotsRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *GetAccountDailySnapshotsRequest) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type GetAccountDailySnapshotsResponse struct {
	AccountDailySnapshots []*AccountDailySnapshot `protobuf:"bytes,1,rep,name=account_daily_snapshots,json=accountDailySnapshots,proto3" json:"account_daily_snapshots,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *GetAccountDailySnapshotsResponse) Reset()         { *m = GetAccountDailySnapshotsResponse{} }
func (m *GetAccountDailySnapshotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountDailySnapshotsResponse) ProtoMessage()    {}
func (*GetAccountDailySnapshotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{3}
}

func (m *GetAccountDailySnapshotsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDailySnapshotsResponse.Unmarshal(m, b)
}
func (m *GetAccountDailySnapshotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDailySnapshotsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountDailySnapshotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDailySnapshotsResponse.Merge(m, src)
}
func (m *GetAccountDailySnapshotsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountDailySnapshotsResponse.Size(m)
}
func (m *GetAccountDailySnapshotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDailySnapshotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDailySnapshotsResponse proto.InternalMessageInfo

func (m *GetAccountDailySnapshotsResponse) GetAccountDailySnapshots() []*AccountDailySnapshot {
	if m != nil {
		return m.AccountDailySnapshots
	}
	return nil
}

type GetAccountMonthlySnapshotsRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AccountId            int64    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountMonthlySnapshotsRequest) Reset()         { *m = GetAccountMonthlySnapshotsRequest{} }
func (m *GetAccountMonthlySnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountMonthlySnapshotsRequest) ProtoMessage()    {}
func (*GetAccountMonthlySnapshotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{4}
}

func (m *GetAccountMonthlySnapshotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountMonthlySnapshotsRequest.Unmarshal(m, b)
}
func (m *GetAccountMonthlySnapshotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountMonthlySnapshotsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountMonthlySnapshotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountMonthlySnapshotsRequest.Merge(m, src)
}
func (m *GetAccountMonthlySnapshotsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountMonthlySnapshotsRequest.Size(m)
}
func (m *GetAccountMonthlySnapshotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountMonthlySnapshotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountMonthlySnapshotsRequest proto.InternalMessageInfo

func (m *GetAccountMonthlySnapshotsRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *GetAccountMonthlySnapshotsRequest) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type GetAccountMonthlySnapshotsResponse struct {
	AccountMonthlySnapshots []*AccountMonthlySnapshot `protobuf:"bytes,1,rep,name=account_monthly_snapshots,json=accountMonthlySnapshots,proto3" json:"account_monthly_snapshots,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                  `json:"-"`
	XXX_unrecognized        []byte                    `json:"-"`
	XXX_sizecache           int32                     `json:"-"`
}

func (m *GetAccountMonthlySnapshotsResponse) Reset()         { *m = GetAccountMonthlySnapshotsResponse{} }
func (m *GetAccountMonthlySnapshotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountMonthlySnapshotsResponse) ProtoMessage()    {}
func (*GetAccountMonthlySnapshotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{5}
}

func (m *GetAccountMonthlySnapshotsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountMonthlySnapshotsResponse.Unmarshal(m, b)
}
func (m *GetAccountMonthlySnapshotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountMonthlySnapshotsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountMonthlySnapshotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountMonthlySnapshotsResponse.Merge(m, src)
}
func (m *GetAccountMonthlySnapshotsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountMonthlySnapshotsResponse.Size(m)
}
func (m *GetAccountMonthlySnapshotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountMonthlySnapshotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountMonthlySnapshotsResponse proto.InternalMessageInfo

func (m *GetAccountMonthlySnapshotsResponse) GetAccountMonthlySnapshots() []*AccountMonthlySnapshot {
	if m != nil {
		return m.AccountMonthlySnapshots
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a5d0ea3f8dbe2a8, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AccountDailySnapshot)(nil), "dataprocessing.AccountDailySnapshot")
	proto.RegisterType((*AccountMonthlySnapshot)(nil), "dataprocessing.AccountMonthlySnapshot")
	proto.RegisterType((*GetAccountDailySnapshotsRequest)(nil), "dataprocessing.GetAccountDailySnapshotsRequest")
	proto.RegisterType((*GetAccountDailySnapshotsResponse)(nil), "dataprocessing.GetAccountDailySnapshotsResponse")
	proto.RegisterType((*GetAccountMonthlySnapshotsRequest)(nil), "dataprocessing.GetAccountMonthlySnapshotsRequest")
	proto.RegisterType((*GetAccountMonthlySnapshotsResponse)(nil), "dataprocessing.GetAccountMonthlySnapshotsResponse")
	proto.RegisterType((*Empty)(nil), "dataprocessing.Empty")
}

func init() {
	proto.RegisterFile("services/dataprocessing/dataProcessing.proto", fileDescriptor_0a5d0ea3f8dbe2a8)
}

var fileDescriptor_0a5d0ea3f8dbe2a8 = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x9d, 0x6e, 0xbb, 0x6b, 0x8f, 0x68, 0xe9, 0x68, 0x6d, 0xba, 0x20, 0xc6, 0x20, 0x25,
	0x14, 0x9b, 0xe8, 0xfa, 0x04, 0x96, 0x15, 0x5d, 0x41, 0x94, 0xf4, 0xca, 0x0f, 0x08, 0x93, 0xcc,
	0xb0, 0x09, 0x24, 0x33, 0x31, 0x33, 0x51, 0x72, 0xa5, 0x37, 0x82, 0x8f, 0xe1, 0xf3, 0x79, 0xed,
	0x03, 0xc8, 0x4c, 0x36, 0x6a, 0xe2, 0xc6, 0x8f, 0x4a, 0xef, 0xf6, 0xe4, 0xfc, 0xe7, 0x7f, 0xe6,
	0x77, 0xce, 0xec, 0x81, 0x3b, 0x92, 0x95, 0x6f, 0xd3, 0x98, 0x49, 0x9f, 0x12, 0x45, 0x8a, 0x52,
	0xc4, 0x4c, 0xca, 0x94, 0x2f, 0x4d, 0xf8, 0xfc, 0x7b, 0xe8, 0x15, 0xa5, 0x50, 0x02, 0x5f, 0xe9,
	0x8a, 0x9c, 0x2f, 0x08, 0xae, 0x3d, 0x88, 0x63, 0x51, 0x71, 0x35, 0x27, 0x69, 0x56, 0x9f, 0x72,
	0x52, 0xc8, 0x44, 0x28, 0xbc, 0x0f, 0x93, 0x54, 0xb1, 0x3c, 0x4c, 0xa9, 0x85, 0x6c, 0xe4, 0x8e,
	0x82, 0xb1, 0x0e, 0x17, 0x14, 0xdf, 0x00, 0x20, 0xcd, 0x01, 0x9d, 0xdb, 0x30, 0xb9, 0xed, 0xd5,
	0x97, 0x05, 0xc5, 0x18, 0x36, 0x29, 0x51, 0xcc, 0x1a, 0xd9, 0xc8, 0xdd, 0x0e, 0xcc, 0x6f, 0x7c,
	0x04, 0xbb, 0x52, 0x91, 0x52, 0x85, 0x94, 0xd4, 0x61, 0x44, 0x32, 0xc2, 0x63, 0x66, 0x6d, 0xda,
	0xc8, 0x45, 0xc1, 0x8e, 0x49, 0xcc, 0x49, 0x7d, 0xd2, 0x7c, 0xc6, 0x87, 0xb0, 0xc3, 0x38, 0xed,
	0x28, 0xb7, 0x8c, 0xf2, 0x32, 0xe3, 0xf4, 0x27, 0xdd, 0x01, 0x5c, 0x8c, 0x89, 0x4c, 0x42, 0x51,
	0x29, 0x6b, 0x6c, 0x04, 0x13, 0x1d, 0x3f, 0xab, 0xcc, 0xd5, 0x4d, 0x2a, 0xe5, 0xd6, 0xc4, 0x64,
	0xc6, 0x3a, 0x5c, 0x70, 0xe7, 0x2b, 0x82, 0xeb, 0x2b, 0xd8, 0xa7, 0x82, 0xab, 0xe4, 0x9c, 0x70,
	0x3d, 0xb8, 0xda, 0xe0, 0xe6, 0xba, 0x48, 0x0f, 0xb8, 0xe9, 0x84, 0x29, 0xdf, 0xa2, 0x1c, 0xc1,
	0xae, 0x46, 0xee, 0xaa, 0x1b, 0x68, 0xdd, 0x8b, 0x8e, 0xf6, 0x2c, 0xd8, 0x2f, 0xe0, 0xe6, 0x23,
	0xa6, 0xd6, 0x4d, 0x59, 0x06, 0xec, 0x4d, 0xc5, 0xe4, 0x99, 0xf1, 0x9d, 0x0f, 0x08, 0xec, 0x61,
	0x6f, 0x59, 0x08, 0x2e, 0x19, 0x7e, 0x0d, 0xfb, 0xad, 0x07, 0xd5, 0x8a, 0x50, 0xb6, 0x12, 0x0b,
	0xd9, 0x23, 0xf7, 0xd2, 0xec, 0xb6, 0xd7, 0x7d, 0x95, 0xde, 0x3a, 0xbf, 0x60, 0x8f, 0xac, 0xab,
	0xe2, 0xbc, 0x82, 0x5b, 0x3f, 0x6e, 0xd0, 0x1b, 0xeb, 0x7f, 0xf3, 0x7d, 0x42, 0xe0, 0xfc, 0xce,
	0x7d, 0x45, 0x18, 0xc1, 0x41, 0xeb, 0x92, 0x37, 0x9a, 0x5f, 0x18, 0x0f, 0x07, 0x18, 0x7b, 0x9e,
	0x41, 0xdb, 0xaa, 0x7e, 0x2d, 0x67, 0x02, 0x5b, 0x0f, 0xf3, 0x42, 0xd5, 0xb3, 0xcf, 0x1b, 0xb0,
	0x37, 0xef, 0xfc, 0xb7, 0x4f, 0x9b, 0x0d, 0x80, 0xdf, 0x83, 0x35, 0x34, 0x0c, 0xec, 0xf7, 0xeb,
	0xff, 0xe1, 0x49, 0x4c, 0xef, 0xfe, 0xfd, 0x81, 0xa6, 0x0b, 0xce, 0x05, 0xfc, 0x11, 0xc1, 0x74,
	0xb8, 0x5d, 0xf8, 0xde, 0xb0, 0xe5, 0xc0, 0xe0, 0xa6, 0xb3, 0x7f, 0x39, 0xd2, 0xde, 0xe3, 0xe4,
	0xc9, 0xcb, 0xc7, 0xcb, 0x54, 0x25, 0x55, 0xe4, 0xc5, 0x22, 0xf7, 0x39, 0x63, 0x59, 0x9c, 0x88,
	0x8a, 0x26, 0xa4, 0xac, 0xfd, 0xa8, 0xa2, 0x4b, 0xa6, 0xde, 0x91, 0x2c, 0x63, 0xea, 0x98, 0x14,
	0xe9, 0xb1, 0xde, 0x9f, 0xac, 0xf4, 0x07, 0xd6, 0x68, 0x34, 0x36, 0x8b, 0xf3, 0xfe, 0xb7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x2d, 0x07, 0x50, 0x1e, 0x68, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataProcessingServiceClient is the client API for DataProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataProcessingServiceClient interface {
	GetAccountDailySnapshots(ctx context.Context, in *GetAccountDailySnapshotsRequest, opts ...grpc.CallOption) (*GetAccountDailySnapshotsResponse, error)
	GetAccountMonthlySnapshots(ctx context.Context, in *GetAccountMonthlySnapshotsRequest, opts ...grpc.CallOption) (*GetAccountMonthlySnapshotsResponse, error)
}

type dataProcessingServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataProcessingServiceClient(cc *grpc.ClientConn) DataProcessingServiceClient {
	return &dataProcessingServiceClient{cc}
}

func (c *dataProcessingServiceClient) GetAccountDailySnapshots(ctx context.Context, in *GetAccountDailySnapshotsRequest, opts ...grpc.CallOption) (*GetAccountDailySnapshotsResponse, error) {
	out := new(GetAccountDailySnapshotsResponse)
	err := c.cc.Invoke(ctx, "/dataprocessing.DataProcessingService/GetAccountDailySnapshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataProcessingServiceClient) GetAccountMonthlySnapshots(ctx context.Context, in *GetAccountMonthlySnapshotsRequest, opts ...grpc.CallOption) (*GetAccountMonthlySnapshotsResponse, error) {
	out := new(GetAccountMonthlySnapshotsResponse)
	err := c.cc.Invoke(ctx, "/dataprocessing.DataProcessingService/GetAccountMonthlySnapshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProcessingServiceServer is the server API for DataProcessingService service.
type DataProcessingServiceServer interface {
	GetAccountDailySnapshots(context.Context, *GetAccountDailySnapshotsRequest) (*GetAccountDailySnapshotsResponse, error)
	GetAccountMonthlySnapshots(context.Context, *GetAccountMonthlySnapshotsRequest) (*GetAccountMonthlySnapshotsResponse, error)
}

// UnimplementedDataProcessingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataProcessingServiceServer struct {
}

func (*UnimplementedDataProcessingServiceServer) GetAccountDailySnapshots(ctx context.Context, req *GetAccountDailySnapshotsRequest) (*GetAccountDailySnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountDailySnapshots not implemented")
}
func (*UnimplementedDataProcessingServiceServer) GetAccountMonthlySnapshots(ctx context.Context, req *GetAccountMonthlySnapshotsRequest) (*GetAccountMonthlySnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountMonthlySnapshots not implemented")
}

func RegisterDataProcessingServiceServer(s *grpc.Server, srv DataProcessingServiceServer) {
	s.RegisterService(&_DataProcessingService_serviceDesc, srv)
}

func _DataProcessingService_GetAccountDailySnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountDailySnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProcessingServiceServer).GetAccountDailySnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataprocessing.DataProcessingService/GetAccountDailySnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProcessingServiceServer).GetAccountDailySnapshots(ctx, req.(*GetAccountDailySnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataProcessingService_GetAccountMonthlySnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountMonthlySnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProcessingServiceServer).GetAccountMonthlySnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataprocessing.DataProcessingService/GetAccountMonthlySnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProcessingServiceServer).GetAccountMonthlySnapshots(ctx, req.(*GetAccountMonthlySnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataProcessingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dataprocessing.DataProcessingService",
	HandlerType: (*DataProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountDailySnapshots",
			Handler:    _DataProcessingService_GetAccountDailySnapshots_Handler,
		},
		{
			MethodName: "GetAccountMonthlySnapshots",
			Handler:    _DataProcessingService_GetAccountMonthlySnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/dataprocessing/dataProcessing.proto",
}
