// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/webhooks/webhooks.proto

package webhooks

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPlaidWebhookRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlaidWebhookRequest) Reset()         { *m = GetPlaidWebhookRequest{} }
func (m *GetPlaidWebhookRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlaidWebhookRequest) ProtoMessage()    {}
func (*GetPlaidWebhookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb006064fc3a36, []int{0}
}

func (m *GetPlaidWebhookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlaidWebhookRequest.Unmarshal(m, b)
}
func (m *GetPlaidWebhookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlaidWebhookRequest.Marshal(b, m, deterministic)
}
func (m *GetPlaidWebhookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlaidWebhookRequest.Merge(m, src)
}
func (m *GetPlaidWebhookRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlaidWebhookRequest.Size(m)
}
func (m *GetPlaidWebhookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlaidWebhookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlaidWebhookRequest proto.InternalMessageInfo

func (m *GetPlaidWebhookRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type GetPlaidWebhookResponse struct {
	Webhook              string   `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlaidWebhookResponse) Reset()         { *m = GetPlaidWebhookResponse{} }
func (m *GetPlaidWebhookResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlaidWebhookResponse) ProtoMessage()    {}
func (*GetPlaidWebhookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb006064fc3a36, []int{1}
}

func (m *GetPlaidWebhookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlaidWebhookResponse.Unmarshal(m, b)
}
func (m *GetPlaidWebhookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlaidWebhookResponse.Marshal(b, m, deterministic)
}
func (m *GetPlaidWebhookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlaidWebhookResponse.Merge(m, src)
}
func (m *GetPlaidWebhookResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlaidWebhookResponse.Size(m)
}
func (m *GetPlaidWebhookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlaidWebhookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlaidWebhookResponse proto.InternalMessageInfo

func (m *GetPlaidWebhookResponse) GetWebhook() string {
	if m != nil {
		return m.Webhook
	}
	return ""
}

type UpdatePlaidWebhookRequest struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Webhook              string   `protobuf:"bytes,2,opt,name=webhook,proto3" json:"webhook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlaidWebhookRequest) Reset()         { *m = UpdatePlaidWebhookRequest{} }
func (m *UpdatePlaidWebhookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlaidWebhookRequest) ProtoMessage()    {}
func (*UpdatePlaidWebhookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb006064fc3a36, []int{2}
}

func (m *UpdatePlaidWebhookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlaidWebhookRequest.Unmarshal(m, b)
}
func (m *UpdatePlaidWebhookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlaidWebhookRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePlaidWebhookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlaidWebhookRequest.Merge(m, src)
}
func (m *UpdatePlaidWebhookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlaidWebhookRequest.Size(m)
}
func (m *UpdatePlaidWebhookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlaidWebhookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlaidWebhookRequest proto.InternalMessageInfo

func (m *UpdatePlaidWebhookRequest) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *UpdatePlaidWebhookRequest) GetWebhook() string {
	if m != nil {
		return m.Webhook
	}
	return ""
}

type UpdatePlaidWebhookResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlaidWebhookResponse) Reset()         { *m = UpdatePlaidWebhookResponse{} }
func (m *UpdatePlaidWebhookResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePlaidWebhookResponse) ProtoMessage()    {}
func (*UpdatePlaidWebhookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8eb006064fc3a36, []int{3}
}

func (m *UpdatePlaidWebhookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlaidWebhookResponse.Unmarshal(m, b)
}
func (m *UpdatePlaidWebhookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlaidWebhookResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePlaidWebhookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlaidWebhookResponse.Merge(m, src)
}
func (m *UpdatePlaidWebhookResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePlaidWebhookResponse.Size(m)
}
func (m *UpdatePlaidWebhookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlaidWebhookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlaidWebhookResponse proto.InternalMessageInfo

func (m *UpdatePlaidWebhookResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*GetPlaidWebhookRequest)(nil), "webhooks.GetPlaidWebhookRequest")
	proto.RegisterType((*GetPlaidWebhookResponse)(nil), "webhooks.GetPlaidWebhookResponse")
	proto.RegisterType((*UpdatePlaidWebhookRequest)(nil), "webhooks.UpdatePlaidWebhookRequest")
	proto.RegisterType((*UpdatePlaidWebhookResponse)(nil), "webhooks.UpdatePlaidWebhookResponse")
}

func init() { proto.RegisterFile("services/webhooks/webhooks.proto", fileDescriptor_f8eb006064fc3a36) }

var fileDescriptor_f8eb006064fc3a36 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x34, 0x0a, 0x6d, 0x7d, 0x97, 0xc2, 0x1e, 0x6c, 0xcd, 0x29, 0x46, 0x0f, 0x5e, 0x9a, 0xa0,
	0x05, 0x3f, 0xa0, 0x08, 0xe2, 0x45, 0x24, 0x22, 0x8a, 0x17, 0xd9, 0xec, 0x3e, 0x9a, 0xc5, 0xb4,
	0x1b, 0xf3, 0x76, 0x2d, 0xfe, 0xa4, 0xdf, 0x24, 0x4d, 0xba, 0x46, 0x4d, 0x0d, 0x78, 0xcb, 0x84,
	0x99, 0x79, 0xb3, 0xc3, 0x40, 0x40, 0x58, 0xbe, 0x29, 0x81, 0x14, 0xaf, 0x30, 0xcd, 0xb4, 0x7e,
	0x69, 0x3e, 0xa2, 0xa2, 0xd4, 0x46, 0xb3, 0x81, 0xc3, 0xe1, 0x19, 0x1c, 0x5c, 0xa1, 0xb9, 0xcd,
	0xb9, 0x92, 0x0f, 0xf5, 0xbf, 0x04, 0x5f, 0x2d, 0x92, 0x61, 0x23, 0xe8, 0x2b, 0x83, 0x8b, 0x67,
	0x25, 0xc7, 0x5e, 0xe0, 0x9d, 0xee, 0x25, 0xbd, 0x35, 0xbc, 0x96, 0xe1, 0x14, 0x46, 0x2d, 0x09,
	0x15, 0x7a, 0x49, 0xc8, 0xc6, 0xd0, 0xdf, 0x38, 0x57, 0x9a, 0xfd, 0xc4, 0xc1, 0xf0, 0x06, 0x0e,
	0xef, 0x0b, 0xc9, 0x0d, 0xfe, 0xe7, 0xd4, 0x77, 0xbf, 0xdd, 0x9f, 0x7e, 0x17, 0xe0, 0x6f, 0xf3,
	0x6b, 0x72, 0x90, 0x15, 0x02, 0x89, 0x2a, 0xc3, 0x41, 0xe2, 0xe0, 0xf9, 0x87, 0x07, 0xc3, 0x0d,
	0x9b, 0xee, 0xea, 0x9a, 0xd8, 0x23, 0x0c, 0x7f, 0x3d, 0x88, 0x05, 0xd1, 0x57, 0x63, 0xdb, 0xeb,
	0xf1, 0x8f, 0x3a, 0x18, 0x75, 0x8a, 0x70, 0x87, 0x71, 0x60, 0xed, 0x94, 0xec, 0xb8, 0x91, 0xfe,
	0xd9, 0x89, 0x7f, 0xd2, 0x4d, 0x72, 0x27, 0x66, 0x97, 0x4f, 0xb3, 0xb9, 0x32, 0x99, 0x4d, 0x23,
	0xa1, 0x17, 0xf1, 0x12, 0x31, 0x17, 0x99, 0xb6, 0x32, 0xe3, 0xe5, 0x7b, 0x9c, 0x5a, 0x39, 0x47,
	0xb3, 0xe2, 0x79, 0x8e, 0x66, 0xc2, 0x0b, 0x35, 0x59, 0x0f, 0x03, 0xcb, 0xb8, 0xb5, 0x8f, 0xb4,
	0x57, 0xed, 0x62, 0xfa, 0x19, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xa8, 0xb8, 0xfa, 0x3b, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebhooksServiceClient is the client API for WebhooksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebhooksServiceClient interface {
	GetPlaidWebhook(ctx context.Context, in *GetPlaidWebhookRequest, opts ...grpc.CallOption) (*GetPlaidWebhookResponse, error)
	UpdatePlaidWebhook(ctx context.Context, in *UpdatePlaidWebhookRequest, opts ...grpc.CallOption) (*UpdatePlaidWebhookResponse, error)
}

type webhooksServiceClient struct {
	cc *grpc.ClientConn
}

func NewWebhooksServiceClient(cc *grpc.ClientConn) WebhooksServiceClient {
	return &webhooksServiceClient{cc}
}

func (c *webhooksServiceClient) GetPlaidWebhook(ctx context.Context, in *GetPlaidWebhookRequest, opts ...grpc.CallOption) (*GetPlaidWebhookResponse, error) {
	out := new(GetPlaidWebhookResponse)
	err := c.cc.Invoke(ctx, "/webhooks.WebhooksService/GetPlaidWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhooksServiceClient) UpdatePlaidWebhook(ctx context.Context, in *UpdatePlaidWebhookRequest, opts ...grpc.CallOption) (*UpdatePlaidWebhookResponse, error) {
	out := new(UpdatePlaidWebhookResponse)
	err := c.cc.Invoke(ctx, "/webhooks.WebhooksService/UpdatePlaidWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhooksServiceServer is the server API for WebhooksService service.
type WebhooksServiceServer interface {
	GetPlaidWebhook(context.Context, *GetPlaidWebhookRequest) (*GetPlaidWebhookResponse, error)
	UpdatePlaidWebhook(context.Context, *UpdatePlaidWebhookRequest) (*UpdatePlaidWebhookResponse, error)
}

// UnimplementedWebhooksServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWebhooksServiceServer struct {
}

func (*UnimplementedWebhooksServiceServer) GetPlaidWebhook(ctx context.Context, req *GetPlaidWebhookRequest) (*GetPlaidWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaidWebhook not implemented")
}
func (*UnimplementedWebhooksServiceServer) UpdatePlaidWebhook(ctx context.Context, req *UpdatePlaidWebhookRequest) (*UpdatePlaidWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlaidWebhook not implemented")
}

func RegisterWebhooksServiceServer(s *grpc.Server, srv WebhooksServiceServer) {
	s.RegisterService(&_WebhooksService_serviceDesc, srv)
}

func _WebhooksService_GetPlaidWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaidWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhooksServiceServer).GetPlaidWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webhooks.WebhooksService/GetPlaidWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhooksServiceServer).GetPlaidWebhook(ctx, req.(*GetPlaidWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhooksService_UpdatePlaidWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlaidWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhooksServiceServer).UpdatePlaidWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webhooks.WebhooksService/UpdatePlaidWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhooksServiceServer).UpdatePlaidWebhook(ctx, req.(*UpdatePlaidWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebhooksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webhooks.WebhooksService",
	HandlerType: (*WebhooksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlaidWebhook",
			Handler:    _WebhooksService_GetPlaidWebhook_Handler,
		},
		{
			MethodName: "UpdatePlaidWebhook",
			Handler:    _WebhooksService_UpdatePlaidWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/webhooks/webhooks.proto",
}
